### ISSUE TITLE
listview item 复用 时间会错乱

### ISSUE THREAD

**Issue by BelieveIDo** [erehmi/CountDownTask#2]

**Comment by erehmi** [comment]
请参考 [https://github.com/erehmi/CountDownTask/blob/master/samples/src/main/java/io/github/erehmi/samples/CountDownAdapter.java](CountDownAdapter.java)

由于AdapterView & RecyclerView的视图重用机制, 因此 getView(...)时, 若当前View不需要倒计时, 需要及时cancel掉倒计时.
